/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/activities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search activities
         * @description Search for activities matching the specified filters.
         *     Results are paginated and ordered by schedule time.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter activities suitable for this age (>= 0) */
                    age?: number;
                    /**
                     * @description Filter by geographic area UUID. Matches activities in the given area
                     *     or any descendant area (for example a region or district).
                     */
                    area_id?: string;
                    /** @description Return results for a single activity UUID (at most one row). */
                    activity_id?: string;
                    /**
                     * @description Filter by activity category UUID. Multiple values allowed; results
                     *     match any listed category.
                     */
                    category_id?: string[];
                    /**
                     * @description Filter by pricing type:
                     *     - per_class: Individual class pricing
                     *     - per_sessions: Per term pricing
                     *     - per_hour: Hourly pricing
                     *     - per_day: Daily pricing
                     *     - free: Free pricing
                     */
                    pricing_type?: "per_class" | "per_sessions" | "per_hour" | "per_day" | "free";
                    /** @description Minimum price filter (>= 0) */
                    price_min?: number;
                    /** @description Maximum price filter (>= 0) */
                    price_max?: number;
                    /**
                     * @description Filter by schedule type:
                     *     - weekly: Recurring weekly schedules
                     */
                    schedule_type?: "weekly";
                    /**
                     * @description Filter by day of week (0-6):
                     *     0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday.
                     */
                    day_of_week_utc?: number;
                    /**
                     * @description Filter by start time (0-1439 minutes from midnight UTC).
                     *     Example: 600 = 10:00 AM UTC.
                     *     Must be less than end_minutes_utc when both provided.
                     */
                    start_minutes_utc?: number;
                    /**
                     * @description Filter by end time (0-1439 minutes from midnight UTC).
                     *     Example: 1080 = 6:00 PM UTC.
                     *     Must be greater than start_minutes_utc when both provided.
                     */
                    end_minutes_utc?: number;
                    /**
                     * @description Filter by language (ISO 639-1 codes plus yue (ISO 639-3)). Multiple values allowed.
                     *     Supported: en, zh, ja, ko, fr, de, es, pt, it, ru, ar, hi, th, vi, id, ms, tl, nl, pl, tr, yue
                     */
                    language?: ("en" | "zh" | "ja" | "ko" | "fr" | "de" | "es" | "pt" | "it" | "ru" | "ar" | "hi" | "th" | "vi" | "id" | "ms" | "tl" | "nl" | "pl" | "tr" | "yue")[];
                    /** @description Maximum results per page (1-200, default 50) */
                    limit?: number;
                    /** @description Pagination cursor from previous response's next_cursor field */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivitySearchResponse"];
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listing-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest first-party listing funnel events
         * @description Record search, listing view, CTA tap, and lead events used to
         *     fill `listing_events_daily` / `v_funnel_daily`. This is first-party
         *     product telemetry (location-grained). The Executive Board already
         *     reads GA4 via its `web` tools; do not send page titles, search
         *     terms, or other PII here.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ListingEventIngestRequest"];
                };
            };
            responses: {
                /** @description Events accepted (duplicates of client_event_id ignored) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Human-readable error message */
            error: string;
        };
        ListingEventIngestRequest: {
            events: components["schemas"]["ListingEvent"][];
        };
        ListingEvent: {
            /** @enum {string} */
            event_type: "search" | "listing_view" | "cta_tap" | "lead_relayed";
            /** @enum {string} */
            source: "public_www" | "flutter" | "partner";
            /**
             * Format: uuid
             * @description Venue UUID. Omit for unattributed events (searches, site-wide
             *     CTAs); the server stores the nil UUID.
             */
            location_id?: string;
            /** Format: uuid */
            activity_id?: string;
            /** @description Client-generated idempotency key. */
            client_event_id?: string;
        };
        ActivitySearchResponse: {
            items: components["schemas"]["ActivitySearchResult"][];
            next_cursor?: string | null;
        };
        ActivitySearchResult: {
            activity: components["schemas"]["Activity"];
            organization: components["schemas"]["Organization"];
            location: components["schemas"]["Location"];
            pricing: components["schemas"]["Pricing"];
            schedule: components["schemas"]["Schedule"];
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            name_translations: components["schemas"]["TranslationMap"];
            description_translations: components["schemas"]["TranslationMap"];
            /** @description Cognito user sub of the organization manager */
            manager_id: string;
            media_urls: string[];
            /**
             * Format: uri
             * @description Optional logo media URL.
             */
            logo_media_url?: string | null;
        };
        Location: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Geographic area UUID (leaf district node)
             */
            area_id: string;
            /**
             * Format: uuid
             * @description Macro-region ancestor UUID (for example Hong Kong Island) when the
             *     location district belongs to a region node.
             */
            region_area_id?: string | null;
            address?: string | null;
            lat?: number | null;
            lng?: number | null;
        };
        Activity: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            name_translations: components["schemas"]["TranslationMap"];
            description_translations: components["schemas"]["TranslationMap"];
            age_min?: number | null;
            age_max?: number | null;
            /**
             * Format: uuid
             * @description Activity category UUID
             */
            category_id?: string;
        };
        Pricing: {
            /** @enum {string} */
            pricing_type: "per_class" | "per_sessions" | "per_hour" | "per_day" | "free";
            amount: number;
            /** @description ISO 4217 currency code (case-insensitive) */
            currency: string;
            sessions_count?: number | null;
            /** @description Whether a free trial class is offered */
            free_trial_class_offered: boolean;
        };
        WeeklyScheduleEntry: {
            day_of_week_utc: number;
            start_minutes_utc: number;
            end_minutes_utc: number;
        };
        Schedule: {
            /** @enum {string} */
            schedule_type: "weekly";
            weekly_entries: components["schemas"]["WeeklyScheduleEntry"][];
            languages: string[];
        };
        /**
         * @description Language map for translated text. The server always includes English as "en".
         *     Additional entries must use ISO 639-1 codes plus "yue" (Cantonese, ISO 639-3).
         */
        TranslationMap: {
            [key: string]: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
